
FILES = asynctest nbtest load50 mapcmp polltest mapper setlevel setconsole inp outp \
	datasize dataalign netifdebug

CFLAGS = -O2 -fomit-frame-pointer -Wall

all: $(FILES)

clean:
	rm -f $(FILES) *~ core

